<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 * @copyright ©2009-2015
 */
namespace Spiral\Components\Session\Http;

use Psr\Http\Message\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Spiral\Components\Http\Cookies\CookieManager;
use Spiral\Components\Http\MiddlewareInterface;
use Spiral\Components\Session\SessionStore;
use Spiral\Core\Container;

class SessionStarter implements MiddlewareInterface
{
    /**
     * Cookie to store session ID in.
     */
    const COOKIE = 'session';

    /**
     * CookieManager
     *
     * @var CookieManager
     */
    protected $cookies = null;

    /**
     * Container used to resolve session store.
     *
     * @var Container
     */
    protected $container = null;

    /**
     * Session store instance.
     *
     * @var SessionStore
     */
    protected $store = null;

    /**
     * Middleware constructing.
     *
     * @param CookieManager $cookies
     * @param Container     $container
     */
    public function __construct(CookieManager $cookies, Container $container)
    {
        $this->cookies = $cookies;
        $this->container = $container;
    }

    /**
     * Manually set session store instance.
     *
     * @param SessionStore $store
     */
    public function setStore(SessionStore $store)
    {
        $this->store = $store;
    }

    /**
     * Get session store instance.
     *
     * @return SessionStore
     */
    public function getStore()
    {
        if (!empty($this->store))
        {
            return $this->store;
        }

        return $this->store = SessionStore::getInstance($this->container);
    }

    /**
     * Handle request generate response. Middleware used to alter incoming Request and/or Response
     * generated by inner pipeline layers.
     *
     * @param ServerRequestInterface $request Server request instance.
     * @param \Closure               $next    Next middleware/target.
     * @return ResponseInterface
     */
    public function __invoke(ServerRequestInterface $request, \Closure $next = null)
    {
        $cookies = $request->getCookieParams();

        if (isset($cookies[self::COOKIE]))
        {
            //Mounting ID retrieved from cookies
            $this->getStore()->setID($cookies[self::COOKIE]);
        }

        $response = $next();

        if (empty($this->store) && is_object($this->container->getBinding(SessionStore::getAlias())))
        {
            //Store were started by itself
            $this->setStore($this->container->get(SessionStore::getAlias()));
        }

        if (!empty($this->store) && ($this->store->isStarted() || $this->store->isDestroyed()))
        {
            return $this->commitSession($this->store, $response, $cookies);
        }

        return $response;
    }

    /**
     * Mount session id or remove session cookie.
     *
     * @param SessionStore      $store
     * @param ResponseInterface $response
     * @param array             $cookies
     * @return ResponseInterface
     */
    protected function commitSession(SessionStore $store, ResponseInterface $response, array $cookies)
    {
        $store->isStarted() && $store->commit();

        if (!isset($cookies[self::COOKIE]) || $cookies[self::COOKIE] != $store->getID())
        {
            if ($response instanceof ResponseInterface)
            {
                return $response->withAddedHeader(
                    'Set-Cookie',
                    $this->cookies->create(
                        self::COOKIE,
                        $store->getID(),
                        $store->getConfig()['lifetime']
                    )
                );
            }
        }

        return $response;
    }
}