coverage:
  status:
    project:
      default:
        target: 80%    # the required coverage value
        threshold: 2%  # the leniency in hitting the target
        informational: true
    patch:
      default:
        target: 80%    # the required coverage value
        threshold: 2%  # the leniency in hitting the target
        informational: true
ignore:
  - ".github"
  - "bin"
  - "resources"
  - "tests"
  - "*"
