<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 * @copyright ©2009-2015
 */
namespace Spiral\Components\Http\Router;

use Predis\Response\ResponseInterface;
use Psr\Http\Message\ServerRequestInterface;
use Spiral\Components\Http\MiddlewareInterface;
use Spiral\Components\Http\Response\Redirect;
use Spiral\Core\Component;
use Spiral\Core\Container;
use Spiral\Core\CoreInterface;

class Router extends Component implements MiddlewareInterface
{
    /**
     * Internal name for default route. Default route used to resolve url and perform controller
     * based routing in cases where no other route found.
     *
     * Default route should support <controller> and <action> parameters. Basically this is multi
     * controller route.
     */
    const DEFAULT_ROUTE = 'default';

    /**
     * Container.
     *
     * @invisible
     * @var Container
     */
    protected $container = null;

    /**
     * Core/Application instance is required to execute controllers (if route has controller as it's
     * target).
     *
     * @invisible
     * @var CoreInterface
     */
    protected $core = null;

    /**
     * Registered routes.
     *
     * @var RouteInterface[]
     */
    protected $routes = array();

    /**
     * Set of route specific middlewares aliases by short string name. This technique allows developer
     * to assign middleware for group of routes.
     *
     * @var array|MiddlewareInterface[]|callable[]
     */
    protected $middlewareAliases = array();

    /**
     * Base path fetched automatically from request attribute "activePath" which is populated by
     * HttpDispatcher while selecting appropriate endpoint. Base path used to correctly resolve route
     * url and pattern when website or module associated with non empty URI path.
     *
     * @var string
     */
    protected $activePath = '/';

    /**
     * Active route instance, this value will be populated only after router successfully handled
     * incoming request.
     *
     * @var RouteInterface|null
     */
    protected $activeRoute = null;


    /**
     * Create new middleware alias which can be used in any route by it's short name.
     *
     * @param string                       $alias
     * @param callable|MiddlewareInterface $middleware
     */
    public function addMiddleware($alias, $middleware)
    {
        $this->middlewareAliases[$alias] = $middleware;
    }

    /**
     * Handle request generate response. Middleware used to alter incoming Request and/or Response
     * generated by inner pipeline layers.
     *
     * @param ServerRequestInterface $request Server request instance.
     * @param \Closure               $next    Next middleware/target.
     * @param object|null            $context Pipeline context, can be HttpDispatcher, Route or module.
     * @return ResponseInterface
     */
    public function __invoke(ServerRequestInterface $request, \Closure $next = null, $context = null)
    {
        //Open router scope
        $outerRouter = $this->container->getBinding('router');
        $this->container->bind('router', $this);

        $this->activePath = $request->getAttribute('activePath', $this->activePath);
        if (!$this->activeRoute = $this->findRoute($request, $this->activePath))
        {
            throw new RouterException("No routes matched given request.");
        }

        //Executing found route
        $response = $this->activeRoute->perform($request, $this->core, $this->middlewareAliases);

        //Close router scope
        $this->container->removeBinding('router');
        !empty($outerRouter) && $this->container->bind('router', $outerRouter);

        return $response;
    }

    /**
     * Find route matched for given request.
     *
     * @param ServerRequestInterface $request
     * @param string                 $basePath
     * @return null|RouteInterface
     */
    protected function findRoute(ServerRequestInterface $request, $basePath)
    {
        foreach ($this->routes as $route)
        {
            if ($route->match($request, $basePath))
            {
                return $route;
            }
        }

        return null;
    }

    /**
     * Add new Route instance to router stack, route has to be added before router handled request.
     *
     * @param RouteInterface $route
     */
    public function addRoute(RouteInterface $route)
    {
        $this->routes[] = $route;
    }

    /**
     * All registered routes.
     *
     * @return RouteInterface[]
     */
    public function getRoutes()
    {
        return $this->routes;
    }

    /**
     * Get currently active route, this value will be populated only after router successfully handled
     * incoming request.
     *
     * @return RouteInterface|null
     */
    public function activeRoute()
    {
        return $this->activeRoute;
    }

    /**
     * Generate url using route name and set of provided parameters. Parameters will be automatically
     * injected to route pattern and prefixed with activePath value.
     *
     * You can enter controller::action type route, in this case appropriate controller and action
     * will be injected into default route as controller and action parameters accordingly.
     *
     * Example:
     * $this->router->url('post::view', ['id' => 1]);
     *
     * @param string $route      Route name.
     * @param array  $parameters Route parameters including controller name, action and etc.
     * @return string
     * @throws RouterException
     */
    public function url($route, array $parameters = array())
    {
        if (!isset($this->routes[$route]))
        {
            //Will be handled via default route where route name is specified as controller::action
            if (strpos($route, '::'))
            {
                throw new RouterException(
                    "Unable to locate route or use default route with controller::action pattern."
                );
            }

            list($controller, $action) = explode('::', $route);
            $parameters = compact('controller', 'action') + $parameters;

            $route = self::DEFAULT_ROUTE;
        }

        return $this->routes[$route]->buildURL($parameters, $this->activePath);
    }

    /**
     * Generate redirect based on url rendered using specified route pattern.
     *
     * You can enter controller::action type route, in this case appropriate controller and action
     * will be injected into default route as controller and action parameters accordingly.
     *
     * Example:
     * return $this->router->redirect('post::view', ['id' => 1]);
     *
     * @param string $route      Route name.
     * @param array  $parameters Route parameters including controller name, action and etc.
     * @return Redirect
     */
    public function redirect($route, array $parameters = array())
    {
        return new Redirect($this->url($route, $parameters));
    }
}