<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 * @copyright ©2009-2015
 */
namespace Spiral\Components\Http\Middlewares;

use Psr\Http\Message\RequestInterface;
use Spiral\Components\Http\MiddlewareInterface;
use Spiral\Components\Http\Response;
use Spiral\Core\Component;

class CRSFToken extends Component implements MiddlewareInterface
{
    /**
     * Handle request generate response. Middleware used to alter incoming Request and/or Response
     * generated by inner pipeline layers.
     *
     * @param RequestInterface $request Request instance.
     * @param \Closure         $next    Next middleware/target.
     * @param object|null      $context Pipeline context, can be HttpDispatcher, Route or module.
     * @return Response
     */
    public function handle(RequestInterface $request, \Closure $next, $context = null)
    {
        return $next();
    }
}