<?php

# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: service.proto

namespace Spiral\Tests\Serializer\Fixture;

use Google\Protobuf\Internal\GPBUtil;

/**
 * Generated from protobuf message <code>ping.dto.PingRequest</code>
 */
class PingRequest extends \Google\Protobuf\Internal\Message
{
    /**
     * Generated from protobuf field <code>string url = 1;</code>
     */
    protected $url = '';

    /**
     * Constructor.
     *
     * @param array $data {
     *     Optional. Data for populating the Message object.
     *
     *     @type string $url
     * }
     */
    public function __construct($data = null)
    {
        \Spiral\Tests\Serializer\Fixture\GPBMetadata\Service::initOnce();
        parent::__construct($data);
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @return string
     */
    public function getUrl()
    {
        return $this->url;
    }

    /**
     * Generated from protobuf field <code>string url = 1;</code>
     * @param string $var
     * @return $this
     */
    public function setUrl($var)
    {
        GPBUtil::checkString($var, true);
        $this->url = $var;

        return $this;
    }
}
