<?php
/**
 * Spiral Framework.
 *
 * @license   MIT
 * @author    Anton Titov (Wolfy-J)
 * @copyright ©2009-2015
 */
namespace Spiral\Components\Http;

use Spiral\Core\Component;

class CRSFValidator implements MiddlewareInterface
{
    /**
     * Token have to check in cookies and queries.
     */
    const TOKEN_NAME = 'crsf-token';

    const CSRF_HEADER = 'X-CSRF-Token';

    /**
     * Handle request generate response. Middleware used to alter incoming Request and/or Response
     * generated by inner pipeline layers.
     *
     * @param Request     $request Server request instance.
     * @param \Closure    $next    Next middleware/target.
     * @param object|null $context Pipeline context, can be HttpDispatcher, Route or module.
     * @return Response
     */
    public function __invoke(Request $request, \Closure $next = null, $context = null)
    {
        if (in_array($request->getMethod(), array('GET', 'HEAD', 'OPTIONS')))
        {
            //unfinished
        }

        /**
         * @var Response $response
         */

        return $next($request->withAttribute('crsfToken', base64_encode(openssl_random_pseudo_bytes(32))));
    }
}